const titulo = document.querySelector(".titulo");
const pCabecera = document.querySelector(".pCabecera");
const parrafo1 = document.querySelector("#parrafo1");
const parrafo2 = document.querySelector("#parrafo2");
const parrafo3 = document.querySelector("#parrafo3");


titulo.innerHtml =`TRIBUTO A QUEEN`;
pCabecera.innerHtml = `Banda británica de rock formada en 1970 en Londres por el cantante y pianista Freddie Mercury, el guitarrista Brian May, el baterista Roger Taylor y el bajista John Deacon. Si bien el grupo ha presentado bajas de dos de sus miembros (Mercury, fallecido en 1991, y Deacon, retirado en 1997), los integrantes restantes, Brian May y Roger Taylor, continúan trabajando bajo el nombre Queen, por lo que la banda aún se considera activa.`; 
parrafo1.innerHtml = `La banda ha citado entre sus influencias a artistas estadounidenses como Elvis Presley, The Beach Boys y Jimi Hendrix al igual que grupos de rock británico de la época, como The Beatles, The Rolling Stones, The Who, David Bowie, Pink Floyd y Led Zeppelin. Queen desarrolló un estilo inspirado en varios géneros musicales. Entre los géneros con los que han sido asociados están: rock progresivo, hard rock, glam rock, heavy metal, pop rock,5​ blues rock y rock psicodélico. Queen también ha escrito canciones que fueron inspiradas por géneros que no son típicamente asociados con el rock, como ragtime, ópera, gospel, vodevil y folk.`;
parrafo2.innerHtml = `Queen es también uno de los artistas musicales con mayores ventas a nivel mundial, con 103,8 millones de ventas certificadas, incluyendo 49,7 millones en los Estados Unidos,​ y unas estimaciones de 150 a 200 millones de álbumes en todo el mundo.​ El grupo ha lanzado un total de dieciocho álbumes número uno, dieciocho sencillos número uno y diez DVD números uno en todo el mundo. Ingresados en el Salón de la Fama del Rock en 2001, los cuatro miembros de Queen ingresaron en el Salón de la Fama de los Compositores en 2003. En 2002, "Bohemian Rhapsody" fue votado como el "éxito favorito del Reino Unido de todos los tiempos"  en una encuesta realizada por el libro de los récords Guiness de los sencillos británicos exitosos, y en 2004 la canción ingresó en el Salón de la Fama de los Grammy.​ En 2009, "We Will Rock You" y "We Are the Champions" también fueron incluidos en el Salón de la Fama de los Grammy, y la segunda fue votada canción más popular del mundo en una encuesta musical a nivel global.`;
parrafo3.innerHtml = `Ampliamente reconocidos por su rock de estadio, en 2005 una encuesta de la industria colocó el concierto de Queen en el Live Aid en 1985 como la mejor actuación en vivo de la historia. En 2007, también fueron votados como la mejor banda británica de la historia por los oyentes de BBC Radio 2.153​ Rolling Stone colocó a Queen en el número 52 de su lista de los "100 mejores artistas de todos los tiempos",​ mientras que Mercury se situó en el puesto 18 en la lista de mejores cantantes,​ y May en el lugar 26 en la lista de mejores guitarristas.​ Queen fue nombrado decimotercer mejor artista de hard rock de todos los tiempos en una lista elaborada por VH1,18​ y en 2010 fueron colocados en el puesto 17 en la lista de VH1 de los 100 mejores artistas de todos los tiempos.`;